### PR TITLE
Updated to Google production access (beta is deprecated)

### PR DESCRIPTION
**Pull request by spleck**
Attached are tweaks I needed to make in order to access production google storage.  This is my first time submitting a pull request, so be gentle but please let me know anything I could have done differently both in the code and in the process.  Thanks!

### CODE REVIEW

**Comment by cebjyre** [comment]
Awesome! I'll try to make this a non-sucky process for you. As may be apparent, it's been a while since I did work on this, so I don't actually have the full testing configs etc immediately available (I've got an idea where it might still exist, but it'll take a bit of time (hours, not days) to access).

How would you prefer to be credited for the contribution? I was thinking a new file like https://metacpan.org/source/PJF/autodie-2.29/AUTHORS - as you can see there's a bit of mix of real names, CPAN usernames, and both.

Cheers

**Comment by spleck** [comment]
Thanks, and as far as any contributor listing Kevin Smith is fine, I appreciate it. :)

**Comment by cebjyre** [comment]
Thanks for your work (there was some extra stuff I needed to do to get my tests working, hence the delay) - this is going up to CPAN as v0.2.0 now

**Comment by spleck** [comment]
That's a pretty smooth process.. thanks!

**Comment by spleck** [comment]
Oh I see you found several changes I didn't see that were needed.. thanks again for the update.

**Pull request merged**
